homepage:
 path: /
 controller: App\Controller\IndexController::home

save_product:
 path: /article/save
 controller: App\Controller\IndexController::save
 
new_article:
 path: /article/new
 controller: App\Controller\IndexController::new
 
article_list:
  path: /article_list
  controller: App\Controller\IndexController::home

article_show:
  path: /article/{id}
  controller: App\Controller\IndexController::show

edit_article:
  path: /article/edit/{id}
  controller: App\Controller\IndexController::edit

delete_article:
  path: /article/delete/{id}
  controller: App\Controller\IndexController::delete

new_category:
  path: /category/newCat
  controller: App\Controller\IndexController::newCategory

article_par_cat:
    path: /art_cat/
    controller: App\Controller\IndexController::articlesParCategorie
    
article_par_prix:
  path: /art_prix/
  controller: App\Controller\IndexController::articlesParPrix
  